#!/bin/bash

function PrintUsage() {
	AppName=`basename $0`
	
	echo "ДЕЛАЙ ТАК:"
	echo "    ${AppName} --add         Добавить запись в книгу стихов."
	echo "    ${AppName} --edit        Открыть книгу стихов (или --open)."
	echo "    ${AppName} --open        Открыть книгу стихов (или --edit)."
	echo "    ${AppName} --help        Помощь."
}

if [ $# -ne 1 ]; then
	PrintUsage
	exit 1
fi

Action=$1
ConfFile=~/.avgdiary/avgdiary.conf

test -f "${ConfFile}" && . ${ConfFile}

if test -z "${avg_diary_dir}"; then
	echo "Нужно установить переменную \${avg_diary_dir} следующим образом."
	echo "export avg_diary_dir=<dir>"
	exit 1
fi

if ! test -d "${avg_diary_dir}"; then
	echo "Не получается найти каталог с дневником \"${avg_diary_dir}\"."
	echo "Установите переменную \${avg_diary_dir} к существующему каталогу."
	echo "export avg_diary_dir=<dir>"
	exit 1
fi

# DirName1=`dirname`
# 
# if test "${DirName1}" == "."; then
# 	Path1=`pwd`
# else
# 	Path1="${DirName1}"
# fi

lyrics_file="${avg_diary_dir}/lyrics.txt"

function FileAddEntry() {
cat >> $lyrics_file << _EOF




                         *  *  *



                             `date +"%H:%M, %d.%m.%Y, %A"`
_EOF
	vim -c "normal Gkk" $lyrics_file
}

function FileOpen() {
	vim $lyrics_file
}

case $Action in
--add)         FileAddEntry ;;
--edit)        FileOpen ;;
--open)        FileOpen ;;
--help)        PrintUsage ;;
*)
	echo Неизвестное действие ${Action}
	PrintUsage
	exit 1
esac
