#!/usr/bin/env perl

use 5.12.0;
use strict;




my $time_log_fullname = "/var/log/time.log";




sub check_lines {
	my $line;
	my $status;
	
	
	open TIME_LOG, "<${time_log_fullname}" or die "не получается открыть ${time_log_fullname}. $!.\n";
	
	while ($line = <TIME_LOG>) {
		chomp $line;
		given ($line) {
			when (/start\.$/ or /stop\.$/) {
				$status = "YES";
			}
			default {
				$status = "NO";
			}
		}
		printf "%s .. %s\n", $line, $status;
	}
	close TIME_LOG or die $!;
}

sub convert {
	my $line;
	my $line1;
	my $time_log_out_fullname = "/tmp/time.log";
	
	
	open TIME_LOG, "<${time_log_fullname}" or die "не получается открыть ${time_log_fullname}. $!.\n";
	open TIME_LOG_OUT, ">${time_log_out_fullname}" or die "не получается открыть ${time_log_out_fullname}. $!.\n";
	
	while ($line = <TIME_LOG>) {
		chomp $line;
		$line =~ /([0-9]{2})\.([0-9]{2})\.([0-9]{4})(.*)/;
		$line1 = "${3}\.${2}\.${1}${4}";
		printf TIME_LOG_OUT "%s\n", $line1;
	}
	
	close TIME_LOG or die $!;
	close TIME_LOG_OUT or die $!;
}

printf "avg_diary_dir = '%s'.\n", $ENV{avg_diary_dir};
